//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3649
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmiWaterTower {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalRc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRc() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HmiWaterTower.GlobalRc", typeof(GlobalRc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap dotnet_logo {
            get {
                object obj = ResourceManager.GetObject("dotnet_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap illustrator2017_large_logo {
            get {
                object obj = ResourceManager.GetObject("illustrator2017_large_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InfoBar_HmiSchneider_background_export {
            get {
                object obj = ResourceManager.GetObject("InfoBar_HmiSchneider_background_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_GEII_sigle_blanc {
            get {
                object obj = ResourceManager.GetObject("logo_GEII_sigle_blanc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_GEII_sigle_rvb {
            get {
                object obj = ResourceManager.GetObject("logo_GEII_sigle_rvb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_IUT_Annecy_BLANC_RVB {
            get {
                object obj = ResourceManager.GetObject("logo_IUT_Annecy_BLANC_RVB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_IUT_Annecy_RVB {
            get {
                object obj = ResourceManager.GetObject("logo_IUT_Annecy_RVB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo_USMB_2015_rvb {
            get {
                object obj = ResourceManager.GetObject("Logo_USMB_2015_rvb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_help_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_help_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_help_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_help_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_help_20px {
            get {
                object obj = ResourceManager.GetObject("picto_help_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_help_3x {
            get {
                object obj = ResourceManager.GetObject("picto_help_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_link_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_link_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_20px {
            get {
                object obj = ResourceManager.GetObject("picto_link_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_3x {
            get {
                object obj = ResourceManager.GetObject("picto_link_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_missing_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_link_missing_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_missing_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_link_missing_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_link_missing_3x {
            get {
                object obj = ResourceManager.GetObject("picto_link_missing_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_refresh_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_refresh_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_refresh_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_refresh_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_refresh_20px {
            get {
                object obj = ResourceManager.GetObject("picto_refresh_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_refresh_3x {
            get {
                object obj = ResourceManager.GetObject("picto_refresh_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_blue_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_round_blue_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_blue_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_round_blue_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_blue_3x {
            get {
                object obj = ResourceManager.GetObject("picto_round_blue_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_green_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_round_green_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_green_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_round_green_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_green_3x {
            get {
                object obj = ResourceManager.GetObject("picto_round_green_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_grey_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_round_grey_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_grey_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_round_grey_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_grey_3x {
            get {
                object obj = ResourceManager.GetObject("picto_round_grey_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_orange_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_round_orange_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_orange_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_round_orange_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_orange_3x {
            get {
                object obj = ResourceManager.GetObject("picto_round_orange_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_red_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_round_red_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_red_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_round_red_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_round_red_3x {
            get {
                object obj = ResourceManager.GetObject("picto_round_red_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_3x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_red_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_red_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_red_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_red_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_red_3x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_red_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_white_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_white_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_white_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_white_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_critical_white_3x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_critical_white_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_disabled_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_disabled_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_disabled_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_disabled_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_disabled_3x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_disabled_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_full_0_5x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_full_0_5x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_full_0_75x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_full_0_75x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picto_warning_full_3x {
            get {
                object obj = ResourceManager.GetObject("picto_warning_full_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue {
            get {
                object obj = ResourceManager.GetObject("process_vue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue_2x {
            get {
                object obj = ResourceManager.GetObject("process_vue_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue_3x {
            get {
                object obj = ResourceManager.GetObject("process_vue_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue_white {
            get {
                object obj = ResourceManager.GetObject("process_vue_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue_white_2x {
            get {
                object obj = ResourceManager.GetObject("process_vue_white_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap process_vue_white_3x {
            get {
                object obj = ResourceManager.GetObject("process_vue_white_3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap schneider_electric_large_logo {
            get {
                object obj = ResourceManager.GetObject("schneider_electric_large_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telemecanique_large_logo {
            get {
                object obj = ResourceManager.GetObject("telemecanique_large_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vs2012_large_logo {
            get {
                object obj = ResourceManager.GetObject("vs2012_large_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
